#!/bin/csh

foreach f ( sensmg.log for xs1 adj sma smf \
            sens_rr_r sens_rr_x senslx sensrx senssm \
            misc sources \
            control stopconverged stoponerror \
            diffs lnk3dnt inpi com )
  if ( -e ${f} ) then
    rm -rf ${f}
  endif
end
if ( "`ls | grep -c ' a[0-9][0-9]/'`" != "0" ) then
  rm -rf a??
endif
if ( "`ls | grep -c ' sens_._r'`" != "0" ) then
  rm -rf sens_?_r
endif
if ( "`ls | grep -c ' sens_._x'`" != "0" ) then
  rm -rf sens_?_x
endif
if ( "`ls | grep -c '_o'`" != "0" ) then
  rm -rf *_o
endif
foreach f ( A.sens_k_r A.sens_k_x A.sensmg.log \
            B.sens_k_r B.sens_k_x B.sensmg.log \
            C.sens_k_r C.sens_k_x C.sens_rr_r C.sens_rr_x C.sensmg.log \
            D.sens_k_r D.sens_k_x D.sens_rr_r D.sens_rr_x D.sensmg.log \
            E.sens_k_r E.sens_k_x E.sens_rr_r E.sens_rr_x E.sensmg.log \
            F.sens_a_r F.sens_a_x F.sens_rr_r F.sens_rr_x F.sensmg.log \
            G.sens_l_r G.sens_l_x G.sens_rr_r G.sens_rr_x G.sensmg.log \
            H.sens_l_r H.sens_l_x H.sensmg.log \
            I.sens_l_r I.sens_l_x I.sens_s_r I.sens_s_x I.sensmg.log \
            J.sens_k_r J.sens_k_x J.sens_rr_r J.sens_rr_x J.sensmg.log \
            K.sens_k_r K.sens_k_x K.sens_rr_r K.sens_rr_x K.sensmg.log \
            Y.sens_k_r Y.sens_k_x Y.sensmg.log \
            Z.sens_l_r Z.sens_l_x Z.sens_s_r Z.sens_s_x Z.sensmg.log )
  rm -f ${f}
end
