#!/bin/csh

foreach f ( sensmg.log for xs1 adj sma smf \
            sens_rr_r sens_rr_x senslx senssm \
            misc sources \
            control stopconverged stoponerror \
            diffs )
  if ( -e ${f} ) then
    rm -f ${f}
  endif
end
rm -f a??
rm -f sens_?_r
rm -f sens_?_x
rm -f *_o
foreach f ( A.sens_k_r A.sens_k_x A.sensmg.log \
            B.sens_k_r B.sens_k_x B.sensmg.log \
            C.sens_k_r C.sens_k_x C.sens_rr_r C.sens_rr_x C.sensmg.log \
            D.sens_k_r D.sens_k_x D.sens_rr_r D.sens_rr_x D.sensmg.log \
            E.sens_k_r E.sens_k_x E.sens_rr_r E.sens_rr_x E.sensmg.log \
            F.sens_a_r F.sens_a_x F.sens_rr_r F.sens_rr_x F.sensmg.log \
            G.sens_l_r G.sens_l_x G.sens_rr_r G.sens_rr_x G.sensmg.log \
            H.sens_l_r H.sens_l_x H.sensmg.log \
            I.sens_l_r I.sens_l_x I.sens_s_r I.sens_s_x I.sensmg.log )
  rm -f ${f}
end
