#!/bin/csh
# first do this:
#   difff ; vi diffs
# if all is ok, then update sensmg.log files using this:
#   make_template 2 ; mv_tmp_readme ; difff ; vi diffs

foreach f ( A B C D E F G H I J K Y Z )
  if ( -e ${f}.sensmg.log.tmp ) then
    mv ${f}.sensmg.log.tmp ${f}.sensmg.log
  else
    echo "${f}.sensmg.log.tmp does not exist."
  endif
end

