#!/bin/csh
# setenv SENS_PARTISN /usr/projects/lindet/rel8_29/8_29_32/snow-intel-18.0.5-openmpi-2.1.2/partisn
  setenv SENS_PARTISN /usr/projects/lindet/rel8_31/8_31_37/snow-intel-19.0.4-openmpi-2.1.2/partisn
# set SENSMG="/usr/projects/data/nuclear/working/sensitivities/bin/sensmg.py"
  set SENSMG="/usr/projects/transportapps/users/fave/sensmg/bin/sensmg.py"
# set SENSMG="/usr/projects/transportapps/users/fave/sensmg/tmp/bin/sensmg.py"
  setenv NDI_GENDIR_PATH /usr/projects/data/nuclear/ndi/2.1.3/share/gendir.all

  echo STARTING RUN:  `date "+ %D %H:%M:%S"`
# note: epsi=1.e-2 is used here. published results used 1.e-6.
# note: isn=32 is used here. published results used isn=64
  cp A bck01
  set f="A"
  ${SENSMG} -i bck01 -isn 32 -isct 7 -ngroup 79 -np 16 -rplane 1 -zplane 1 -epsi 1.e-2
  foreach o ( sens_k_x sens_k_r sensmg.log )
    if ( -e ${o} ) then
      mv ${o} ${f}.${o}
    endif
  end
  echo FINISHED RUN:  `date "+ %D %H:%M:%S"`
