#!/bin/csh
  setenv NDI_GENDIR_PATH /usr/projects/data/nuclear/ndi/2.1.3/share/gendir.all
# setenv SENS_PARTISN /usr/projects/lindet/rel8_29/8_29_32/snow-intel-18.0.5-openmpi-2.1.2/partisn
  setenv SENS_PARTISN /usr/projects/lindet/rel8_31/8_31_12/snow-intel-18.0.5-openmpi-2.1.2/partisn
# set SENSMG="/usr/projects/data/nuclear/working/sensitivities/bin/sensmg.py"
  set SENSMG="/usr/projects/transportapps/users/fave/sensmg/bin/sensmg.py"

# note: epsig=1.e-3 is used here. published results used 1.e-5.
# note: isn=8 is used here. published results used isn=32
  echo STARTING RUN:  `date "+ %D %H:%M:%S"`
  set f="C"
  ${SENSMG} -i ${f} -ngroup 70 -isn 8 -epsig 1.e-3
  foreach o ( sens_k_x sens_k_r sens_rr_x sens_rr_r sensmg.log )
    if ( -e ${o} ) then
      mv ${o} ${f}.${o}
    endif
  end
  echo FINISHED RUN:  `date "+ %D %H:%M:%S"`
