#!/bin/csh
# set SENSMG="/usr/projects/data/nuclear/working/sensitivities/bin/sensmg.py"
  set SENSMG="/usr/projects/transportapps/users/fave/sensmg/bin/sensmg.py"
# setenv SENS_PARTISN /usr/projects/lindet/rel8_29/8_29_32/snow-intel-18.0.5-openmpi-2.1.2/partisn
  setenv SENS_PARTISN /usr/projects/lindet/rel8_31/8_31_12/snow-intel-18.0.5-openmpi-2.1.2/partisn

  setenv OMP_NUM_THREADS 1

  set f="G"
  ${SENSMG} -i ${f} -fissdata 2 -srcacc_no for+adj -2nd_order yes
  foreach o ( sens_l_x sens_l_r sens_rr_x sens_rr_r sensmg.log )
    if ( -e ${o} ) then
      mv ${o} ${f}.${o}
    endif
  end

