#!/bin/csh
# set SENSMG="/usr/projects/data/nuclear/working/sensitivities/bin/sensmg.py"
  set SENSMG="/usr/projects/transportapps/users/fave/sensmg/bin/sensmg.py"
# set SENSMG="/usr/projects/transportapps/users/fave/sensmg/bin/sensmg2.py"
  setenv SENS_PARTISN /usr/projects/lindet/rel8_27/8_27_15/snow-intel-17.0.4-openmpi-2.1.2/partisn
# setenv SENS_PARTISN /usr/projects/lindet/ml_intel/bin/partisn_7_72
# setenv SENS_PARTISN /net/scratch3/fave/partisn-5_97/partisn_5_97

  setenv OMP_NUM_THREADS 1

  set f="G"
  ${SENSMG} -i ${f} -fissdata 2 -srcacc_no for+adj 
  foreach o ( sens_l_x sens_l_r sens_rr_x sens_rr_r sensmg.log )
    if ( -e ${o} ) then
      mv ${o} ${f}.${o}
    endif
  end

